spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/labwork1
    username: lab1user
    password: lab1user
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update